### ISSUE TITLE
continuous build script

### ISSUE THREAD

**Issue by laggingreflex** [queckezz/preact-hyperscript#2]
I noticed there's no build script (other than "prepublish") that continuously builds source on modification. Something like "babel --watch"

I usually fork/clone and npm-link dependencies (like this one) in my own project in case I need to dive into them, and so I rely on them having such a continuous build script so that changes I make in them can directly affect my project. 

So it could be really helpful.  Please consider adding such a script.

**Comment by queckezz** [comment]
All code written in this module is compatible with node 6 and above. So if you are testing, just test against node 6 and you'll be fine 👍
