### ISSUE TITLE
Not working with preact's "h"

### ISSUE THREAD

**Issue by laggingreflex** [queckezz/preact-hyperscript#6]
```
import {createElement as h} from 'preact-hyperscript';
import { h as hh } from 'preact';

h('div', [h('div', {}, ['this works'])])
h('div', [hh('div', {}, ['this doesnt work - shows "[object Object]"'])])
```

**Comment by laggingreflex** [comment]
Ah nevermind it does. 

This is a weird problem. I have `preact-hyperscript` repo cloned in `~/forks/preact-hyperscript` and I do `npm link preact-hyperscript` in my main project. So `preact-hyperscript` being in its own directory outside the scope of the project, also has its dependencies installed separately. And since both my project and `preact-hyperscript` use the common dependency `preact` they end up using separate "versions" -- `preact-hyperscript` uses `preact` from its own directory's node_modules and my project uses it from its own  directory's node_modules. I don't know why but this (both using separate "versions" of `preact` (technically same semver but coming from different locations)) creates a problem.

I've seen this in other places as well, with other modules and projects (webpack-dev-server's HMR not working due to same problem comes to mind in a recent issue as it created global variables that don't work if there are separate "versions" running). 

The solution was to simply re-install `preact-hyperscript` in my project, along with all its other dependencies that get flattened with npm resulting in both using the same "version" of preact. 

I think this could be solved if `preact-hyperscript` marked its `preact` dependency as a "peerDependencies" so it doesn't install a separate copy from the project itself. For tests it could have it as in "devDependencies" as well. Although I wouldn't request this as this doesn't seem like something that should *needed* to be done in the first place. I don't know why preact doesn't play well when different "versions" are being used in same project.

**Comment by queckezz** [comment]
Ah yea, it is marked as a `peer dependency` however: https://github.com/queckezz/preact-hyperscript/blob/master/package.json#L30
